// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_z3u5VUirxhbklkvGNT8GDjSr0yQczIQ',
    appId: '1:719997160582:web:e71e3a9c7b1b5ee8f05507',
    messagingSenderId: '719997160582',
    projectId: 'farmlink0403',
    authDomain: 'farmlink0403.firebaseapp.com',
    storageBucket: 'farmlink0403.appspot.com',
    measurementId: 'G-ZX6EZ8CC8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzocBTs0Wct4AjYfuhrMH3pnL4jP0NlW4',
    appId: '1:719997160582:android:0c64ffd2c2573abcf05507',
    messagingSenderId: '719997160582',
    projectId: 'farmlink0403',
    storageBucket: 'farmlink0403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XLtB-_Wnca1nS59j5xITYmscItPeBh0',
    appId: '1:719997160582:ios:e393f86c8e83dd0ff05507',
    messagingSenderId: '719997160582',
    projectId: 'farmlink0403',
    storageBucket: 'farmlink0403.appspot.com',
    iosClientId: '719997160582-nrim3253mlq95mngtnh0cj4ghrbninus.apps.googleusercontent.com',
    iosBundleId: 'com.neelam.farmlink',
  );
}
